// counter
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT'

//wheatherForecasts

export const REQUEST_WEATHER_FORECASTS ='REQUEST_WEATHER_FORECASTS'
export const RECEIVE_WEATHER_FORECASTS ='RECEIVE_WEATHER_FORECASTS'